[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[[redirects]]
  from = "/"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
[[redirects]]
  from = "/"
  to = "/login"
  status = 200
  edge_handler = "filterRequests"

  [[redirects]]
  from = "https://bitbid.netlify.com/register"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
  [[redirects]]
  from = "/login"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
  [[redirects]]
  from = "/"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
  [[redirects]]
  from = "/"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
  [[redirects]]
  from = "/"
  to = "/activate"
  status = 200
  edge_handler = "filterRequests"
 [[redirects]]
  from = "/activate"
  to = "https://flutterwave.com/pay/4cb6328plnky"
  status = 200
  edge_handler = "filterRequests"
   [[redirects]]
  from = "/login"
  to = "/activate"
  status = 200
  edge_handler = "filterRequests"
   [[redirects]]
  from = "/login"
  to = "/dash"
  status = 200
  edge_handler = "filterRequests"
   [[redirects]]
  from = "/https://ravesandbox.flutterwave.com/pay/bitbidpayments"
  to = "https://bitbid.netlify.app/dash#/dash"
  status = 200
  edge_handler = "filterRequests"