[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[[redirects]]
  from = "/"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
[[redirects]]
  from = "/"
  to = "/login"
  status = 200
  edge_handler = "filterRequests"

  [[redirects]]
  from = "https://bitbid.netlify.com/register"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
  [[redirects]]
  from = "/login"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
  [[redirects]]
  from = "/"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
  [[redirects]]
  from = "/"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
  [[redirects]]
  from = "/"
  to = "/payment"
  status = 200
  edge_handler = "filterRequests"
 [[redirects]]
  from = "/payment"
  to = "https://ravesandbox.flutterwave.com/pay/3weo3ps0qjxk"
  status = 200
  edge_handler = "filterRequests"